### ISSUE TITLE
Adding a poll for feedback

### ISSUE THREAD

**Issue by Fergus-Stonehouse** [Fergus-Stonehouse/loverunning#3]
As a **site moderator**, I can **add a poll for any user** so that **feedback can be acquired on new topics**.

##Acceptance Criteria:

- [x] Add specific top title
- [ ] Provide a variable number of options to the poll
- [ ] Allow any user to take part in the poll

### Tasks

- [x] Provide an open Poll Page
- [ ] Make it accessabke for all users and visitors
- [ ] Make options clear but keep options capped.
